import { InvoiceDetailPage } from '@/components/page/Admin/Invoice';
import type { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head';

export interface InvoiceDetailNextPageProps {
  test: string;
}
const InvoiceDetailNextPage: NextPage<InvoiceDetailNextPageProps> = (
  props: InvoiceDetailNextPageProps
) => {
  return (
    <>
      <Head>
        <title>InvoiceDetail Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InvoiceDetailPage {...props} />
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  return {
    props: {
      test: 'test',
    },
  };
};

export default InvoiceDetailNextPage;
