import { InvoiceListPage } from '@/components/page/Admin/Invoice';
import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';

export interface InvoiceListNextPageProps {
  test: string;
}
const InvoiceListNextPage: NextPage<InvoiceListNextPageProps> = (
  props: InvoiceListNextPageProps
) => {
  return (
    <>
      <Head>
        <title>InvoiceList Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InvoiceListPage {...props} />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      test: 'test',
    },
  };
};

export default InvoiceListNextPage;
