version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    restart: always
  mongodb-seed:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    volumes:
      - ./mongo:/mongo
    links:
      - mongodb
    command: mongo/setup.sh
    tty: true
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - 4000
    environment:
      - PORT=4000
      - NODE_ENV=development
    ports:
      - 4000:4000
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    links:
      - mongodb
    restart: always
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - REACT_APP_PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    links:
      - server
    tty: true
  storybook:
    build:
      context: ./client
      dockerfile: Dockerfile.storybook
    environment:
      - NODE_ENV=development
    expose:
      - 6006
    ports:
      - 6006:6006
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
