version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - "server"
      - "client"
    ports:
      - '80:80'
      - '4000:4000'
      - '6006:6006'
  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./mongo:/mongo
      - mongo_data:/data/db
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - "mongodb"
    volumes:
      - ./server:/app/server
      - server_node_modules:/app/server/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    restart: always
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - "server"
    volumes:
      - ./client:/app/client
      - client_node_modules:/app/client/node_modules
      - client_next:/app/client/.next
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    tty: true

volumes:
  mongo_data:
  client_node_modules:
  client_next:
  server_node_modules:

networks:
  default:
    driver: bridge