version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '4000:4000'
  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./mongo:/mongo
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app/server
      - /app/client/node_modules
    environment:
      - NODE_ENV=production
    restart: always
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
      - /app/client/.next
    tty: true
  # storybook:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile.storybook
  #   environment:
  #     - NODE_ENV=development
  #   volumes:
  #     - ./client:/app/client
  #     - /app/client/node_modules
networks:
  default:
    driver: bridge