version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '4000:4000'
      - '6006:6006'
  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./mongo:/mongo
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=4000
      - NODE_ENV=development
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    restart: always
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - REACT_APP_PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    tty: true
  storybook:
    build:
      context: ./client
      dockerfile: Dockerfile.storybook
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/app/client
networks:
  default:
    driver: bridge