import { PromotionDetailPage } from '@/components/page/Admin/Promotion';
import type { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head';

export interface PromotionDetailNextPageProps {
  test: string;
}
const PromotionDetailNextPage: NextPage<PromotionDetailNextPageProps> = (
  props: PromotionDetailNextPageProps
) => {
  return (
    <>
      <Head>
        <title>PromotionDetail Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PromotionDetailPage {...props} />
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  return {
    props: {
      test: 'test',
    },
  };
};

export default PromotionDetailNextPage;
