import { PromotionListPage } from '@/components/page/Admin/Promotion';
import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';

export interface PromotionListNextPageProps {
  test: string;
}
const PromotionListNextPage: NextPage<PromotionListNextPageProps> = (
  props: PromotionListNextPageProps
) => {
  return (
    <>
      <Head>
        <title>PromotionList Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PromotionListPage {...props} />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      test: 'test',
    },
  };
};

export default PromotionListNextPage;
