import { ProductDetailPage } from '@/components/page/Admin/Product';
import type { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head';

export interface ProductDetailNextPageProps {
  test: string;
}
const ProductDetailNextPage: NextPage<ProductDetailNextPageProps> = (
  props: ProductDetailNextPageProps
) => {
  return (
    <>
      <Head>
        <title>ProductDetail Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductDetailPage {...props} />
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  return {
    props: {
      test: 'test',
    },
  };
};

export default ProductDetailNextPage;
