import { ProductListPage } from '@/components/page/Admin/Product';
import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';

export interface ProductListNextPageProps {
  test: string;
}
const ProductListNextPage: NextPage<ProductListNextPageProps> = (
  props: ProductListNextPageProps
) => {
  return (
    <>
      <Head>
        <title>ProductList Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductListPage {...props} />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      test: 'test',
    },
  };
};

export default ProductListNextPage;
