import { DashboardPage } from '@/components/page/Dashboard';
import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';

export interface DashboardNextPageProps {
  test: string;
}
const DashboardNextPage: NextPage<DashboardNextPageProps> = (
  props: DashboardNextPageProps
) => {
  return (
    <>
      <Head>
        <title>Dashboard Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashboardPage {...props} />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      test: 'test',
    },
  };
};

export default DashboardNextPage;
