import { DetailPage } from '@/components/page/Detail';
import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';

export interface DetailNextPageProps {
  test: string;
}
const DetailNextPage: NextPage<DetailNextPageProps> = (
  props: DetailNextPageProps
) => {
  return (
    <>
      <Head>
        <title>Detail Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DetailPage {...props} />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      test: 'test',
    },
  };
};

export default DetailNextPage;
