import { ForgotPasswordPage } from '@/components/page/ForgotPassword';
import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';

export interface ForgotPasswordNextPageProps {
  test: string;
}
const ForgotPasswordNextPage: NextPage<ForgotPasswordNextPageProps> = (
  props: ForgotPasswordNextPageProps
) => {
  return (
    <>
      <Head>
        <title>ForgotPassword Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ForgotPasswordPage {...props} />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      test: 'test',
    },
  };
};

export default ForgotPasswordNextPage;
