import type { NextPage } from 'next';
import Head from 'next/head';
import 'tailwindcss/tailwind.css';
import Link from 'next/link';
import { Button } from '@/components/atoms/Button';
import client from '../apollo-client';
import { GET_PRODUCT_MANY } from '../gql/product';
import { TProduct } from 'types/product';

const Home: NextPage<{ products: [TProduct] }> = ({ products }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <nav>
          <Link href="/about">
            <a>About</a>
          </Link>
          <Button label={'test'} />
        </nav>
      </main>

      <ul>
        {products &&
          products.map((product) => (
            <li key={product._id}>
              {product.name}:{product.user.name}
            </li>
          ))}
      </ul>

      <footer></footer>
    </div>
  );
};

export async function getStaticProps() {
  const { data } = await client.query({
    query: GET_PRODUCT_MANY,
  });

  return {
    props: {
      products: data.productMany,
    },
  };
}

export default Home;
