import { ResetPasswordPage } from '@/components/page/ResetPassword';
import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';

export interface ResetPasswordNextPageProps {
  test: string;
}
const ResetPasswordNextPage: NextPage<ResetPasswordNextPageProps> = (
  props: ResetPasswordNextPageProps
) => {
  return (
    <>
      <Head>
        <title>ResetPassword Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResetPasswordPage {...props} />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      test: 'test',
    },
  };
};

export default ResetPasswordNextPage;
