import { SignUpPage } from '@/components/page/SignUp';
import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';

export interface SignUpNextPageProps {
  test: string;
}
const SignUpNextPage: NextPage<SignUpNextPageProps> = (
  props: SignUpNextPageProps
) => {
  return (
    <>
      <Head>
        <title>SignUp Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignUpPage {...props} />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      test: 'test',
    },
  };
};

export default SignUpNextPage;
