import { SignInPage } from '@/components/page/SignIn';
import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';

export interface SignInNextPageProps {
  test: string;
}
const SignInNextPage: NextPage<SignInNextPageProps> = (
  props: SignInNextPageProps
) => {
  return (
    <>
      <Head>
        <title>SignIn Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignInPage {...props} />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      test: 'test',
    },
  };
};

export default SignInNextPage;
