import { PlanListPage } from '@/components/page/Admin/Plan';
import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';

export interface PlanListNextPageProps {
  test: string;
}
const PlanListNextPage: NextPage<PlanListNextPageProps> = (
  props: PlanListNextPageProps
) => {
  return (
    <>
      <Head>
        <title>PlanList Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PlanListPage {...props} />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      test: 'test',
    },
  };
};

export default PlanListNextPage;
