import { PlanOptionDetailPage } from '@/components/page/Admin/PlanOption';
import type { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head';

export interface PlanOptionDetailNextPageProps {
  test: string;
}
const PlanOptionDetailNextPage: NextPage<PlanOptionDetailNextPageProps> = (
  props: PlanOptionDetailNextPageProps
) => {
  return (
    <>
      <Head>
        <title>PlanOptionDetail Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PlanOptionDetailPage {...props} />
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  return {
    props: {
      test: 'test',
    },
  };
};

export default PlanOptionDetailNextPage;
