import { PlanOptionListPage } from '@/components/page/Admin/PlanOption';
import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';

export interface PlanOptionListNextPageProps {
  test: string;
}
const PlanOptionListNextPage: NextPage<PlanOptionListNextPageProps> = (
  props: PlanOptionListNextPageProps
) => {
  return (
    <>
      <Head>
        <title>PlanOptionList Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PlanOptionListPage {...props} />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      test: 'test',
    },
  };
};

export default PlanOptionListNextPage;
