import { CustomerListPage } from '@/components/page/Admin/Customer';
import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';

export interface CustomerListNextPageProps {
  test: string;
}
const CustomerListNextPage: NextPage<CustomerListNextPageProps> = (
  props: CustomerListNextPageProps
) => {
  return (
    <>
      <Head>
        <title>CustomerList/Customer Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CustomerListPage {...props} />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      test: 'test',
    },
  };
};

export default CustomerListNextPage;
