import { UserProfilePage } from '@/components/page/UserProfile';
import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';

export interface UserProfileNextPageProps {
  test: string;
}
const UserProfileNextPage: NextPage<UserProfileNextPageProps> = (
  props: UserProfileNextPageProps
) => {
  return (
    <>
      <Head>
        <title>UserProfile Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserProfilePage {...props} />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      test: 'test',
    },
  };
};

export default UserProfileNextPage;
