import { CustomerDetailPage } from '@/components/page/Admin/Customer';
import type { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head';

export interface CustomerDetailNextPageProps {
  test: string;
}
const CustomerDetailNextPage: NextPage<CustomerDetailNextPageProps> = (
  props: CustomerDetailNextPageProps
) => {
  return (
    <>
      <Head>
        <title>CustomerDetail Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CustomerDetailPage {...props} />
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  return {
    props: {
      test: 'test',
    },
  };
};

export default CustomerDetailNextPage;
