name: CI/Testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  client_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node@16.7.0
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '16.7.0'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          cd client
          yarn install

      - name: Unit Testing
        run: |
          cd client
          yarn test

      - name: Cypress Run
        uses: cypress-io/github-action@v4
        with:
          working-directory: client
          start: yarn run dev
          wait-on: 'http://localhost:3000'
          config: screenshotOnRunFailure=false,video=false

  server_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node@16.7.0
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '16.7.0'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          cd server
          yarn install

      - name: Unit Testing
        run: |
          cd server
          yarn test
